name: Some Bash

on: [push]
jobs:
  run-windows-commands:
      runs-on: windows-latest
      steps: 
        - name: Directory PowerShell
          run: Get-Location
        - name: Directoy Bahsh
          run: pwd
          shell: bash 